config/routes.rb
Rails.application.routes.draw do

  get 'collaborators/edit'

  get 'collaborators/create'

  get 'charges/new'

  get 'charges/create'

  resources :wikis

  post 'users/update'

  resources :charges, only: [:new, :create]

  devise_for :users

  get 'about' => 'welcome#about'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :collaborators
  has_many :wikis, through: :collaborators

  after_initialize :init

  enum role: [:standard, :admin, :premium]

  def init
    self.role ||= :standard
  end
end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  def public?
    self.private == false
  end

  def owner
    self.user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: Amount.default,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    redirect_to root_path(current_user) # or wherever
    current_user.role = :premium
    current_user.save!

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.

    # This 'rescue block' catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{
      Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.email}",
      amount: Amount.default
    }
  end

  class Amount
    def self.default
      15_00
    end
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def create
    @collaborator = Collaborator.new
    @collaborator.wiki_id = params[:collaborator][:wiki_id]
    @collaborator.user_id = params[:collaborator][:user_id]

    if @collaborator.save
      flash[:notice] = "Collaborator(s) was saved."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error saving the collaborator(s). Please try again."
      redirect_to wikis_path
    end
  end

  def edit
    @collaborator = Collaborator.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def update
    @user = current_user
    @user.role = :standard
    @wikis = Wiki.select {|wiki| wiki.user = @user }
    @wikis.map! do |wiki|
      wiki.private = false
      wiki.save
    end

    if @user.save
      flash[:notice] = "You are now a standard user."
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error updating user role. Please try again."
      redirect_to root_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.user = current_user

    add_collaborators(@wiki, params[:wiki][:collaborator_ids])

    if current_user.standard?
      @wiki.private = false
    else
      @wiki.private = false || true
    end

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    if params[:wiki][:collaborators]
      @wiki.collaborators = []
      add_collaborators(@wiki, params[:wiki][:collaborator_ids])
    end


    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private

  def add_collaborators(wiki, arr)
    arr.map!{|number| number.to_i} unless arr.nil?
    unless arr.nil?
      arr.each do |collaborator|
        unless collaborator == 0
          c = wiki.collaborators.new
          c.user = User.find(collaborator)
          c.save
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
    return markdown.render(text).html_safe
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/create.html.erb
<h1>Collaborators#create</h1>
<p>Find me in app/views/collaborators/create.html.erb</p>

app/views/collaborators/edit.html.erb
<h1>Collaborators#edit</h1>
<p>Find me in app/views/collaborators/edit.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magmapedia</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li>
          <%= link_to '/' do %>
            <%= image_tag("magmapedia_logo.png", { class: "logo" }) %>
          <% end %>
        </li>
        <li><%= link_to "Wikis", wikis_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
      <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong>
    |
        <%= link_to 'Edit profile', edit_user_registration_path,
    :class => 'navbar-link' %> - <%= link_to "Sign Out",
    destroy_user_session_path, method: :delete, :class =>
    'navbar-link' %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path,
    :class => 'navbar-link' %> -
        <%= link_to "Sign In", new_user_session_path, :class =>
    'navbar-link' %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <%= image_tag("magmapedia_logo.png", { class: "logo_main" }) %>
  <p>Social, Markdown Wikis</p>
</div>
<div class="text-center">
  <h3>Create and share Markdown Wikis</h3>
</div>
<br>
<div class="column pull-left">
  <div class="col-md-4 text-center">
      <h4>Create as many public wikis as you want!</h4>
      Free Plan
  </div>
</div>
<div class="column pull right">
  <div class="col-md-4 pull-right text-center">
    <h4>Create private wikis!</h4>
    <div>
      <% if current_user.role == "premium" %>
        <%= link_to "Cancel Premium Plan", users_update_path(current_user), method: :update, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade to standard? If you do, all your private wikis will become public.'} %>
      <% end %>
    </div>
    <div>
      <% if current_user.role == "standard" %>
        <%= link_to "Upgrade to Premium Plan", charges_new_path, class: 'btn btn-success' %>
      <% end %>
    </div>
  </div>
</div>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
      <ul>
        <li>There are no rules.</li>
        <li>Dogs rule.</li>
        <li>Cats want to take over the world.</li>
      </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <% if current_user == @wiki.user %>
        <%= render partial: 'form', locals: { f: f }%>
      <% end %>
      <% if @wiki.private == true && current_user == @wiki.user %>
        <%= f.label :collaborators %>
        <%= f.collection_select(:collaborator_ids, User.all, :id, :email, {selected: @wiki.collaborators.pluck(:user_id)}, {multiple: true})%>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save" %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <%= link_to wiki.title, wiki %>
      </h4>
    </div>
  </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
      <ul>
        <li>There are no rules.</li>
        <li>Dogs rule.</li>
        <li>Cats want to take over the world.</li>
      </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <%= render partial: 'form', locals: { f: f, wiki: @wiki }%>
      <% if current_user.admin? %>
        <%= f.label :collaborators %>
        <%= f.collection_select(:collaborator_ids, User.all, :id, :email, {class: 'foo'}, {multiple: true})%>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save" %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= markdown(@wiki.body) %></p>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are yu sure you want to delete this wiki?'} %>
  </div>
</div>